{% set name = "crunchflow" %}
{% set version = "2.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crunchflow-{{ version }}.tar.gz
  sha256: 7c8251ee7e30f96cf127f12f39ac6f839068ff3b921f2540115bac3b3048729a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - numpy >=2.0.0,<3.0.0
    - matplotlib-base >=3.7.0,<4.0.0
    - pandas >=2.2.2,<3.0.0

test:
  imports:
    - crunchflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/crunchflow/
  summary: A Python toolbox for working with the CrunchFlow reactive transport code
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zperzan
